/*
  Free Download Manager Copyright (c) 2003-2016 FreeDownloadManager.ORG
*/

#include "StdAfx.h"
#include "SignatureDecipheringAlgorithmProvider.h"

std::vector<SignatureDecipheringAlgorithm> SignatureDecipheringAlgorithmProvider::getValues(){
	
	
	std::vector<SignatureDecipheringAlgorithm> algorithms;
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflNzKG7n"), _T( "s3 r s2 r s1 r w67" ) ) );
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfllMCQWM"), _T("s2 w46 r w27 s2 w43 s2 r") ) );			
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflJv8FA8"), _T("s1 w51 w52 r") ) );				
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflR_cX32"), _T("s2 w64 s3") ) );					 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflveGye9"), _T("w21 w3 s1 r w44 w36 r w41 s1") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflj7Fxxt"), _T("r s3 w3 r w17 r w41 r s2") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflDG7-a-"), _T("w52 r s3 w21 r s3 r") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl39KBj1"), _T("w52 r s3 w21 r s3 r") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflmOfVEX"), _T("w52 r s3 w21 r s3 r") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflJwJuHJ"), _T("r s3 w19 r s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl_ymO4Z"), _T("r s3 w19 r s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl26ng3K"), _T("r s2 r") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflcaqGO8"), _T("w24 w53 s2 w31 w4") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflQw-fB4"), _T("s2 r s3 w9 s3 w43 s3 r w23") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflSAFCP9"), _T("r s2 w17 w61 r s1 w7 s1") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflART1Nf"), _T("s3 r w63 s2 r s1") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflLC8JvQ"), _T("w34 w29 w9 r w39 w24") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflm_D8eE"), _T("s2 r w39 w55 w49 s3 w56 w2") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflTWC9KW"), _T("r s2 w65 r") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflRFcHMl"), _T("s3 w24 r") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflM2EmfJ"), _T("w10 r s1 w45 s2 r s3 w50 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflz8giW0"), _T("s2 w18 s3") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl_wGgYV"), _T("w60 s1 r s1 w9 s3 r s3 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl1HXdPb"), _T("w52 r w18 r s1 w44 w51 r s1") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflkn6DAl"), _T("w39 s2 w57 s2 w23 w35 s2") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl2LOvBh"), _T("w34 w19 r s1 r s3 w24 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl-bxy_m"), _T("w48 s3 w37 s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflZK4ZYR"), _T("w19 w68 s1") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflh9ybst"), _T("w48 s3 w37 s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflapUV9V"), _T("s2 w53 r w59 r s2 w41 s3") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflg0g8PQ"), _T("w36 s3 r s2") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflHOr_nV"), _T("w58 r w50 s1 r s1 r w11 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfluy6kdb"), _T("r w12 w32 r w34 s3 w35 w42 s2") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflkuzxcs"), _T("w22 w43 s3 r s1 w43") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflGNjMhJ"), _T("w43 w2 w54 r w8 s1") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfldJ8xgI"), _T("w11 r w29 s1 r s3") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl79wBKW"), _T("s3 r s1 r s3 r s3 w59 s2") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflg3FZfr"), _T("r s3 w66 w10 w43 s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflUKrNpT"), _T("r s2 r w63 r") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfldWnjUz"), _T("r s1 w68") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflP7iCEe"), _T("w7 w37 r s1") ) );					  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflzVne63"), _T("w59 s2 r") ) );					 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflO-N-9M"), _T("w9 s1 w67 r s3") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflZ4JlpT"), _T("s3 r s1 r w28 s1") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflDgXSDS"), _T("s3 r s1 r w28 s1") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflW444Sr"), _T("r w9 r s1 w51 w27 r s1 r") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflK7RoTQ"), _T("w44 r w36 r w45") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflKOCFq2"), _T("s1 r w41 r w41 s1 w15") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflcLL31E"), _T("s1 r w41 r w41 s1 w15") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflz9bT3N"), _T("s1 r w41 r w41 s1 w15") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfliZsE79"), _T("r s3 w49 s3 r w58 s2 r s2") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfljOFtAt"), _T("r s3 r s1 r w69 r") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflqSl9GX"), _T("w32 r s2 w65 w26 w45 w24 w40 s2") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflFrKymJ"), _T("w32 r s2 w65 w26 w45 w24 w40 s2") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflKz4WoM"), _T("w50 w17 r w7 w65") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflhdWW8S"), _T("s2 w55 w10 s3 w57 r w25 w41") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl66X2C5"), _T("r s2 w34 s2 w39") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflCXG8Sm"), _T("r s2 w34 s2 w39") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl_3Uag6"), _T("w3 w7 r s2 w27 s2 w42 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflQdXVwM"), _T("s1 r w66 s2 r w12") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflCtc3aO"), _T("s2 r w11 r s3 w28") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflCt6YZX"), _T("s2 r w11 r s3 w28") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflG49soT"), _T("w32 r s3 r s1 r w19 w24 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl4cHApe"), _T("w25 s1 r s1 w27 w21 s1 w39") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflwMrwdI"), _T("w3 r w39 r w51 s1 w36 w14") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl4AMHqP"), _T("r s1 w1 r w43 r s1 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfln8xPyM"), _T("w36 w14 s1 r s1 w54") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflVSLmnY"), _T("s3 w56 w10 r s2 r w28 w35") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflkLvpg7"), _T("w4 s3 w53 s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflbxes4n"), _T("w4 s3 w53 s2") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflmXMtFI"), _T("w57 s3 w62 w41 s3 r w60 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflYDqEW1"), _T("w24 s1 r s2 w31 w4 w11 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflapGX6Q"), _T("s3 w2 w59 s2 w68 r s3 r s1") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflLCYwkM"), _T("s3 w2 w59 s2 w68 r s3 r s1") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflcY_8N0"), _T("s2 w36 s1 r w18 r w19 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl9qWoOL"), _T("w68 w64 w28 r") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfle-mVwz"), _T("s3 w7 r s3 r w14 w59 s3 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfltdb6U3"), _T("w61 w5 r s2 w69 s2 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflLjFx3B"), _T("w40 w62 r s2 w21 s3 r w7 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfliqjKfF"), _T("w40 w62 r s2 w21 s3 r w7 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflxBu-5R"), _T("w40 w62 r s2 w21 s3 r w7 s3") ) );		
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflrGwWV9"), _T("w36 w45 r s2 r") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflCME3y0"), _T("w8 s2 r w52") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl1LZyZ5"), _T("w8 s2 r w52") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl4_saJa"), _T("r s1 w19 w9 w57 w38 s3 r s2") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflP9269H"), _T("r w63 w37 s3 r w14 r") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflkClbFb"), _T("s1 w12 w24 s1 w52 w70 s2") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflYhChiG"), _T("w27 r s3") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflWnCYSF"), _T("r s1 r s3 w19 r w35 w61 s2") ) );	 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflbT9-GA"), _T("w51 w15 s1 w22 s1 w41 r w43 r") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflAYBrl7"), _T("s2 r w39 w43") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflS1POwl"), _T("w48 s2 r s1 w4 w35") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflLMtkhg"), _T("w30 r w30 w39") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflbJnZqE"), _T("w26 s1 w15 w3 w62 w54 w22") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflgd5txb"), _T("w26 s1 w15 w3 w62 w54 w22") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflTm330y"), _T("w26 s1 w15 w3 w62 w54 w22") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflnwMARr"), _T("s3 r w24 s2") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflTq0XZu"), _T("r w7 s3 w28 w52 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl8s5-Vs"), _T("w26 s1 w14 r s3 w8") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl7i9w86"), _T("w26 s1 w14 r s3 w8") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflA-1YdP"), _T("w26 s1 w14 r s3 w8") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflZwcnOf"), _T("w46 s2 w29 r s2 w51 w20 s1") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflFqBlmB"), _T("w46 s2 w29 r s2 w51 w20 s1") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflG0UvOo"), _T("w46 s2 w29 r s2 w51 w20 s1") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflS6PgfC"), _T("w40 s2 w40 r w56 w26 r s2") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl6Q1v_C"), _T("w23 r s2 w55 s2") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflMYwWq8"), _T("w51 w32 r s1 r s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflGC4r8Z"), _T("w17 w34 w66 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflyEvP6v"), _T("s1 r w26") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflm397e5"), _T("s1 r w26") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfldK8353"), _T("r s3 w32") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflPTD6yH"), _T("w59 s1 w66 s3 w10 r w55 w70 s1") ) );	 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl7KJl0G"), _T("w59 s1 w66 s3 w10 r w55 w70 s1") ) );	  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflhUwbGZ"), _T("w49 r w60 s2 w61 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflzEDYyE"), _T("w49 r w60 s2 w61 s3") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflimfEzR"), _T("r s2 w68 w28") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl_nbW1R"), _T("r w8 r s3") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfll7obaF"), _T("w48 w17 s2") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfluBAJ91"), _T("w13 s1 w39") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfldOnicU"), _T("s2 r w7 w21 r") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflbbaSdm"), _T("w46 r s3 w19 r s2 w15") ) );			 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflIpxel5"), _T("r w16 w35") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfloyxzv5"), _T("r w30 s3 r s3 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflmY-xcZ"), _T("w25 r s1 w49 w52") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflMVaJmz"), _T("w12 s3 w56 r s2 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflgt97Vg"), _T("r s1 r") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl19qQQ_"), _T("s2 w55 s2 r w39 s2 w5 r s3") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflws3c7_"), _T("r s1 w52") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflPqsNqq"), _T("r s1 w52") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflycBCEX"), _T("w12 s1 r s3 w17 s1 w9 r") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflhZC-Jn"), _T("w69 w70 s3") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl9r3Wpv"), _T("r s3 w57") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl6UPpbU"), _T("w37 r s1") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl_oxbbV"), _T("w37 r s1") ) );				  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflXGBaUN"), _T("w37 r s1") ) );				 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflM1arS5"), _T("s1 r w42 r s1 w27 r w54") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl0Cbn9e"), _T("w15 w44 r w24 s3 r w2 w50") ) );		 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vfl5aDZwb"), _T("w15 w44 r w24 s3 r w2 w50") ) );		  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflqZIm5b"), _T("w1 w32 s1 r s3 r s3 r") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflBb0OQx"), _T("w53 r w9 s2 r s1") ) );			  
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflCGk6yw"), _T("s2 w28 w44 w26 w40 w64 r s1") ) ); 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflNUsYw0"), _T("r s3 w7") ) );                     
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflId8cpZ"), _T("w30 w21 w26 s1 r s1 w30 w11 w20") ) );
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflEyBLiy"), _T("w44 r w15 s2 w40 r s1") ) );      
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflHkCS5P"), _T("s2 r s3 r w41 s1 r s1 r") ) );    
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflArxUZc"), _T("r w12 r s3 w14 w61 r") ) ); 
	algorithms.push_back( SignatureDecipheringAlgorithm(_T("vflzfjbJf"), _T("w8 r s2 w37 s1 w21 s3") ) ); 
	return algorithms;
}
